-- Idempotent seed for geo reference data (issue #26).
--
-- Run once per deploy (backend/entrypoint.sh, after `alembic upgrade
-- head`) via `psql`. Safe to re-run indefinitely: each block first
-- checks whether its table already holds rows for that scope and
-- skips entirely if so; every INSERT also carries ON CONFLICT DO
-- NOTHING as a second, row-level safety net (covers a prior run that
-- was interrupted partway through).
--
-- Sources:
--   - Countries: ISO 3166-1 alpha-2.
--   - Indonesia provinces/cities: provinsi.csv + kabupaten_kota.csv from
--     https://github.com/alifbint/indonesia-38-provinsi (kecamatan/
--     kelurahan level from that repo is intentionally NOT imported —
--     out of scope per issue #26, kota/kabupaten is the finest level).
--
-- gen_random_uuid() (built into Postgres 13+ core) stands in for the
-- app-layer uuid7() used elsewhere (ADR-006) — fine for one-off seed
-- rows that are never written by the application's own insert path.
--
-- Manual run (e.g. running the API outside Docker via run.py, against a
-- local Postgres): from backend/, `psql "$DATABASE_URL" -f
-- db/seed/geo_reference_data.sql` — strip the `+asyncpg` driver suffix
-- from DATABASE_URL first if it's set (psql doesn't understand it), e.g.
-- `psql "${DATABASE_URL/postgresql+asyncpg/postgresql}" -f db/seed/geo_reference_data.sql`.

-- ── Countries (ISO 3166-1 alpha-2) ────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM geo_countries LIMIT 1) THEN
    INSERT INTO geo_countries (code, name_en) VALUES
      ('AF', 'Afghanistan'),
      ('AX', 'Aland Islands'),
      ('AL', 'Albania'),
      ('DZ', 'Algeria'),
      ('AS', 'American Samoa'),
      ('AD', 'Andorra'),
      ('AO', 'Angola'),
      ('AI', 'Anguilla'),
      ('AQ', 'Antarctica'),
      ('AG', 'Antigua and Barbuda'),
      ('AR', 'Argentina'),
      ('AM', 'Armenia'),
      ('AW', 'Aruba'),
      ('AU', 'Australia'),
      ('AT', 'Austria'),
      ('AZ', 'Azerbaijan'),
      ('BS', 'Bahamas'),
      ('BH', 'Bahrain'),
      ('BD', 'Bangladesh'),
      ('BB', 'Barbados'),
      ('BY', 'Belarus'),
      ('BE', 'Belgium'),
      ('BZ', 'Belize'),
      ('BJ', 'Benin'),
      ('BM', 'Bermuda'),
      ('BT', 'Bhutan'),
      ('BO', 'Bolivia'),
      ('BQ', 'Bonaire, Sint Eustatius and Saba'),
      ('BA', 'Bosnia and Herzegovina'),
      ('BW', 'Botswana'),
      ('BV', 'Bouvet Island'),
      ('BR', 'Brazil'),
      ('IO', 'British Indian Ocean Territory'),
      ('BN', 'Brunei Darussalam'),
      ('BG', 'Bulgaria'),
      ('BF', 'Burkina Faso'),
      ('BI', 'Burundi'),
      ('CV', 'Cabo Verde'),
      ('KH', 'Cambodia'),
      ('CM', 'Cameroon'),
      ('CA', 'Canada'),
      ('KY', 'Cayman Islands'),
      ('CF', 'Central African Republic'),
      ('TD', 'Chad'),
      ('CL', 'Chile'),
      ('CN', 'China'),
      ('CX', 'Christmas Island'),
      ('CC', 'Cocos (Keeling) Islands'),
      ('CO', 'Colombia'),
      ('KM', 'Comoros'),
      ('CG', 'Congo'),
      ('CD', 'Congo, Democratic Republic of the'),
      ('CK', 'Cook Islands'),
      ('CR', 'Costa Rica'),
      ('CI', 'Cote d''Ivoire'),
      ('HR', 'Croatia'),
      ('CU', 'Cuba'),
      ('CW', 'Curacao'),
      ('CY', 'Cyprus'),
      ('CZ', 'Czechia'),
      ('DK', 'Denmark'),
      ('DJ', 'Djibouti'),
      ('DM', 'Dominica'),
      ('DO', 'Dominican Republic'),
      ('EC', 'Ecuador'),
      ('EG', 'Egypt'),
      ('SV', 'El Salvador'),
      ('GQ', 'Equatorial Guinea'),
      ('ER', 'Eritrea'),
      ('EE', 'Estonia'),
      ('SZ', 'Eswatini'),
      ('ET', 'Ethiopia'),
      ('FK', 'Falkland Islands'),
      ('FO', 'Faroe Islands'),
      ('FJ', 'Fiji'),
      ('FI', 'Finland'),
      ('FR', 'France'),
      ('GF', 'French Guiana'),
      ('PF', 'French Polynesia'),
      ('TF', 'French Southern Territories'),
      ('GA', 'Gabon'),
      ('GM', 'Gambia'),
      ('GE', 'Georgia'),
      ('DE', 'Germany'),
      ('GH', 'Ghana'),
      ('GI', 'Gibraltar'),
      ('GR', 'Greece'),
      ('GL', 'Greenland'),
      ('GD', 'Grenada'),
      ('GP', 'Guadeloupe'),
      ('GU', 'Guam'),
      ('GT', 'Guatemala'),
      ('GG', 'Guernsey'),
      ('GN', 'Guinea'),
      ('GW', 'Guinea-Bissau'),
      ('GY', 'Guyana'),
      ('HT', 'Haiti'),
      ('HM', 'Heard Island and McDonald Islands'),
      ('VA', 'Holy See'),
      ('HN', 'Honduras'),
      ('HK', 'Hong Kong'),
      ('HU', 'Hungary'),
      ('IS', 'Iceland'),
      ('IN', 'India'),
      ('ID', 'Indonesia'),
      ('IR', 'Iran'),
      ('IQ', 'Iraq'),
      ('IE', 'Ireland'),
      ('IM', 'Isle of Man'),
      ('IL', 'Israel'),
      ('IT', 'Italy'),
      ('JM', 'Jamaica'),
      ('JP', 'Japan'),
      ('JE', 'Jersey'),
      ('JO', 'Jordan'),
      ('KZ', 'Kazakhstan'),
      ('KE', 'Kenya'),
      ('KI', 'Kiribati'),
      ('KP', 'Korea, North'),
      ('KR', 'Korea, South'),
      ('KW', 'Kuwait'),
      ('KG', 'Kyrgyzstan'),
      ('LA', 'Laos'),
      ('LV', 'Latvia'),
      ('LB', 'Lebanon'),
      ('LS', 'Lesotho'),
      ('LR', 'Liberia'),
      ('LY', 'Libya'),
      ('LI', 'Liechtenstein'),
      ('LT', 'Lithuania'),
      ('LU', 'Luxembourg'),
      ('MO', 'Macao'),
      ('MG', 'Madagascar'),
      ('MW', 'Malawi'),
      ('MY', 'Malaysia'),
      ('MV', 'Maldives'),
      ('ML', 'Mali'),
      ('MT', 'Malta'),
      ('MH', 'Marshall Islands'),
      ('MQ', 'Martinique'),
      ('MR', 'Mauritania'),
      ('MU', 'Mauritius'),
      ('YT', 'Mayotte'),
      ('MX', 'Mexico'),
      ('FM', 'Micronesia'),
      ('MD', 'Moldova'),
      ('MC', 'Monaco'),
      ('MN', 'Mongolia'),
      ('ME', 'Montenegro'),
      ('MS', 'Montserrat'),
      ('MA', 'Morocco'),
      ('MZ', 'Mozambique'),
      ('MM', 'Myanmar'),
      ('NA', 'Namibia'),
      ('NR', 'Nauru'),
      ('NP', 'Nepal'),
      ('NL', 'Netherlands'),
      ('NC', 'New Caledonia'),
      ('NZ', 'New Zealand'),
      ('NI', 'Nicaragua'),
      ('NE', 'Niger'),
      ('NG', 'Nigeria'),
      ('NU', 'Niue'),
      ('NF', 'Norfolk Island'),
      ('MK', 'North Macedonia'),
      ('MP', 'Northern Mariana Islands'),
      ('NO', 'Norway'),
      ('OM', 'Oman'),
      ('PK', 'Pakistan'),
      ('PW', 'Palau'),
      ('PS', 'Palestine, State of'),
      ('PA', 'Panama'),
      ('PG', 'Papua New Guinea'),
      ('PY', 'Paraguay'),
      ('PE', 'Peru'),
      ('PH', 'Philippines'),
      ('PN', 'Pitcairn'),
      ('PL', 'Poland'),
      ('PT', 'Portugal'),
      ('PR', 'Puerto Rico'),
      ('QA', 'Qatar'),
      ('RE', 'Reunion'),
      ('RO', 'Romania'),
      ('RU', 'Russian Federation'),
      ('RW', 'Rwanda'),
      ('BL', 'Saint Barthelemy'),
      ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
      ('KN', 'Saint Kitts and Nevis'),
      ('LC', 'Saint Lucia'),
      ('MF', 'Saint Martin (French part)'),
      ('PM', 'Saint Pierre and Miquelon'),
      ('VC', 'Saint Vincent and the Grenadines'),
      ('WS', 'Samoa'),
      ('SM', 'San Marino'),
      ('ST', 'Sao Tome and Principe'),
      ('SA', 'Saudi Arabia'),
      ('SN', 'Senegal'),
      ('RS', 'Serbia'),
      ('SC', 'Seychelles'),
      ('SL', 'Sierra Leone'),
      ('SG', 'Singapore'),
      ('SX', 'Sint Maarten (Dutch part)'),
      ('SK', 'Slovakia'),
      ('SI', 'Slovenia'),
      ('SB', 'Solomon Islands'),
      ('SO', 'Somalia'),
      ('ZA', 'South Africa'),
      ('GS', 'South Georgia and the South Sandwich Islands'),
      ('SS', 'South Sudan'),
      ('ES', 'Spain'),
      ('LK', 'Sri Lanka'),
      ('SD', 'Sudan'),
      ('SR', 'Suriname'),
      ('SJ', 'Svalbard and Jan Mayen'),
      ('SE', 'Sweden'),
      ('CH', 'Switzerland'),
      ('SY', 'Syrian Arab Republic'),
      ('TW', 'Taiwan'),
      ('TJ', 'Tajikistan'),
      ('TZ', 'Tanzania'),
      ('TH', 'Thailand'),
      ('TL', 'Timor-Leste'),
      ('TG', 'Togo'),
      ('TK', 'Tokelau'),
      ('TO', 'Tonga'),
      ('TT', 'Trinidad and Tobago'),
      ('TN', 'Tunisia'),
      ('TR', 'Turkiye'),
      ('TM', 'Turkmenistan'),
      ('TC', 'Turks and Caicos Islands'),
      ('TV', 'Tuvalu'),
      ('UG', 'Uganda'),
      ('UA', 'Ukraine'),
      ('AE', 'United Arab Emirates'),
      ('GB', 'United Kingdom'),
      ('US', 'United States'),
      ('UM', 'United States Minor Outlying Islands'),
      ('UY', 'Uruguay'),
      ('UZ', 'Uzbekistan'),
      ('VU', 'Vanuatu'),
      ('VE', 'Venezuela'),
      ('VN', 'Viet Nam'),
      ('VG', 'Virgin Islands (British)'),
      ('VI', 'Virgin Islands (U.S.)'),
      ('WF', 'Wallis and Futuna'),
      ('EH', 'Western Sahara'),
      ('YE', 'Yemen'),
      ('ZM', 'Zambia'),
      ('ZW', 'Zimbabwe')
    ON CONFLICT (code) DO NOTHING;
  END IF;
END $$;

-- ── Indonesia provinces (geo_states) ────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM geo_states WHERE country_code = 'ID' LIMIT 1) THEN
    INSERT INTO geo_states (id, country_code, name, is_active, created_at, updated_at)
    SELECT gen_random_uuid(), 'ID', v.name, true, now(), now()
    FROM (VALUES
      ('Aceh'),
      ('Sumatera Utara'),
      ('Sumatera Barat'),
      ('Riau'),
      ('Jambi'),
      ('Sumatera Selatan'),
      ('Bengkulu'),
      ('Lampung'),
      ('Kepulauan Bangka Belitung'),
      ('Kepulauan Riau'),
      ('DKI Jakarta'),
      ('Jawa Barat'),
      ('Jawa Tengah'),
      ('DI Yogyakarta'),
      ('Jawa Timur'),
      ('Banten'),
      ('Bali'),
      ('Nusa Tenggara Barat'),
      ('Nusa Tenggara Timur'),
      ('Kalimantan Barat'),
      ('Kalimantan Tengah'),
      ('Kalimantan Selatan'),
      ('Kalimantan Timur'),
      ('Kalimantan Utara'),
      ('Sulawesi Utara'),
      ('Sulawesi Tengah'),
      ('Sulawesi Selatan'),
      ('Sulawesi Tenggara'),
      ('Gorontalo'),
      ('Sulawesi Barat'),
      ('Maluku'),
      ('Maluku Utara'),
      ('Papua'),
      ('Papua Barat'),
      ('Papua Selatan'),
      ('Papua Tengah'),
      ('Papua Pegunungan'),
      ('Papua Barat Daya')
    ) AS v(name)
    ON CONFLICT (country_code, name) DO NOTHING;
  END IF;
END $$;

-- ── Indonesia cities/regencies (geo_cities) ──────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM geo_cities WHERE country_code = 'ID' LIMIT 1) THEN
    INSERT INTO geo_cities (id, state_id, country_code, name, is_active, created_at, updated_at)
    SELECT gen_random_uuid(), gs.id, 'ID', v.city_name, true, now(), now()
    FROM (VALUES
      ('Aceh', 'Aceh Selatan'),
      ('Aceh', 'Aceh Tenggara'),
      ('Aceh', 'Aceh Timur'),
      ('Aceh', 'Aceh Tengah'),
      ('Aceh', 'Aceh Barat'),
      ('Aceh', 'Aceh Besar'),
      ('Aceh', 'Pidie'),
      ('Aceh', 'Aceh Utara'),
      ('Aceh', 'Simeulue'),
      ('Aceh', 'Aceh Singkil'),
      ('Aceh', 'Bireuen'),
      ('Aceh', 'Aceh Barat Daya'),
      ('Aceh', 'Gayo Lues'),
      ('Aceh', 'Aceh Jaya'),
      ('Aceh', 'Nagan Raya'),
      ('Aceh', 'Aceh Tamiang'),
      ('Aceh', 'Bener Meriah'),
      ('Aceh', 'Pidie Jaya'),
      ('Aceh', 'Kota Banda Aceh'),
      ('Aceh', 'Kota Sabang'),
      ('Aceh', 'Kota Lhokseumawe'),
      ('Aceh', 'Kota Langsa'),
      ('Aceh', 'Kota Subulussalam'),
      ('Sumatera Utara', 'Tapanuli Tengah'),
      ('Sumatera Utara', 'Tapanuli Utara'),
      ('Sumatera Utara', 'Tapanuli Selatan'),
      ('Sumatera Utara', 'Nias'),
      ('Sumatera Utara', 'Langkat'),
      ('Sumatera Utara', 'Karo'),
      ('Sumatera Utara', 'Deli Serdang'),
      ('Sumatera Utara', 'Simalungun'),
      ('Sumatera Utara', 'Asahan'),
      ('Sumatera Utara', 'Labuhanbatu'),
      ('Sumatera Utara', 'Dairi'),
      ('Sumatera Utara', 'Toba'),
      ('Sumatera Utara', 'Mandailing Natal'),
      ('Sumatera Utara', 'Nias Selatan'),
      ('Sumatera Utara', 'Pakpak Bharat'),
      ('Sumatera Utara', 'Humbang Hasundutan'),
      ('Sumatera Utara', 'Samosir'),
      ('Sumatera Utara', 'Serdang Bedagai'),
      ('Sumatera Utara', 'Batu Bara'),
      ('Sumatera Utara', 'Padang Lawas Utara'),
      ('Sumatera Utara', 'Padang Lawas'),
      ('Sumatera Utara', 'Labuhanbatu Selatan'),
      ('Sumatera Utara', 'Labuhanbatu Utara'),
      ('Sumatera Utara', 'Nias Utara'),
      ('Sumatera Utara', 'Nias Barat'),
      ('Sumatera Utara', 'Kota Medan'),
      ('Sumatera Utara', 'Kota Pematangsiantar'),
      ('Sumatera Utara', 'Kota Sibolga'),
      ('Sumatera Utara', 'Kota Tanjung Balai'),
      ('Sumatera Utara', 'Kota Binjai'),
      ('Sumatera Utara', 'Kota Tebing Tinggi'),
      ('Sumatera Utara', 'Kota Padangsidimpuan'),
      ('Sumatera Utara', 'Kota Gunungsitoli'),
      ('Sumatera Barat', 'Pesisir Selatan'),
      ('Sumatera Barat', 'Solok'),
      ('Sumatera Barat', 'Sijunjung'),
      ('Sumatera Barat', 'Tanah Datar'),
      ('Sumatera Barat', 'Padang Pariaman'),
      ('Sumatera Barat', 'Agam'),
      ('Sumatera Barat', 'Lima Puluh Kota'),
      ('Sumatera Barat', 'Pasaman'),
      ('Sumatera Barat', 'Kepulauan Mentawai'),
      ('Sumatera Barat', 'Dharmasraya'),
      ('Sumatera Barat', 'Solok Selatan'),
      ('Sumatera Barat', 'Pasaman Barat'),
      ('Sumatera Barat', 'Kota Padang'),
      ('Sumatera Barat', 'Kota Solok'),
      ('Sumatera Barat', 'Kota Sawahlunto'),
      ('Sumatera Barat', 'Kota Padang Panjang'),
      ('Sumatera Barat', 'Kota Bukittinggi'),
      ('Sumatera Barat', 'Kota Payakumbuh'),
      ('Sumatera Barat', 'Kota Pariaman'),
      ('Riau', 'Kampar'),
      ('Riau', 'Indragiri Hulu'),
      ('Riau', 'Bengkalis'),
      ('Riau', 'Indragiri Hilir'),
      ('Riau', 'Pelalawan'),
      ('Riau', 'Rokan Hulu'),
      ('Riau', 'Rokan Hilir'),
      ('Riau', 'Siak'),
      ('Riau', 'Kuantan Singingi'),
      ('Riau', 'Kepulauan Meranti'),
      ('Riau', 'Kota Pekanbaru'),
      ('Riau', 'Kota Dumai'),
      ('Jambi', 'Kerinci'),
      ('Jambi', 'Merangin'),
      ('Jambi', 'Sarolangun'),
      ('Jambi', 'Batanghari'),
      ('Jambi', 'Muaro Jambi'),
      ('Jambi', 'Tanjung Jabung Barat'),
      ('Jambi', 'Tanjung Jabung Timur'),
      ('Jambi', 'Bungo'),
      ('Jambi', 'Tebo'),
      ('Jambi', 'Kota Jambi'),
      ('Jambi', 'Kota Sungai Penuh'),
      ('Sumatera Selatan', 'Ogan Komering Ulu'),
      ('Sumatera Selatan', 'Ogan Komering Ilir'),
      ('Sumatera Selatan', 'Muara Enim'),
      ('Sumatera Selatan', 'Lahat'),
      ('Sumatera Selatan', 'Musi Rawas'),
      ('Sumatera Selatan', 'Musi Banyuasin'),
      ('Sumatera Selatan', 'Banyuasin'),
      ('Sumatera Selatan', 'Ogan Komering Ulu Timur'),
      ('Sumatera Selatan', 'Ogan Komering Ulu Selatan'),
      ('Sumatera Selatan', 'Ogan Ilir'),
      ('Sumatera Selatan', 'Empat Lawang'),
      ('Sumatera Selatan', 'Penukal Abab Lematang Ilir'),
      ('Sumatera Selatan', 'Musi Rawas Utara'),
      ('Sumatera Selatan', 'Kota Palembang'),
      ('Sumatera Selatan', 'Kota Pagar Alam'),
      ('Sumatera Selatan', 'Kota Lubuk Linggau'),
      ('Sumatera Selatan', 'Kota Prabumulih'),
      ('Bengkulu', 'Bengkulu Selatan'),
      ('Bengkulu', 'Rejang Lebong'),
      ('Bengkulu', 'Bengkulu Utara'),
      ('Bengkulu', 'Kaur'),
      ('Bengkulu', 'Seluma'),
      ('Bengkulu', 'Muko Muko'),
      ('Bengkulu', 'Lebong'),
      ('Bengkulu', 'Kepahiang'),
      ('Bengkulu', 'Bengkulu Tengah'),
      ('Bengkulu', 'Kota Bengkulu'),
      ('Lampung', 'Lampung Selatan'),
      ('Lampung', 'Lampung Tengah'),
      ('Lampung', 'Lampung Utara'),
      ('Lampung', 'Lampung Barat'),
      ('Lampung', 'Tulang Bawang'),
      ('Lampung', 'Tanggamus'),
      ('Lampung', 'Lampung Timur'),
      ('Lampung', 'Way Kanan'),
      ('Lampung', 'Pesawaran'),
      ('Lampung', 'Pringsewu'),
      ('Lampung', 'Mesuji'),
      ('Lampung', 'Tulang Bawang Barat'),
      ('Lampung', 'Pesisir Barat'),
      ('Lampung', 'Kota Bandar Lampung'),
      ('Lampung', 'Kota Metro'),
      ('Kepulauan Bangka Belitung', 'Bangka'),
      ('Kepulauan Bangka Belitung', 'Belitung'),
      ('Kepulauan Bangka Belitung', 'Bangka Selatan'),
      ('Kepulauan Bangka Belitung', 'Bangka Tengah'),
      ('Kepulauan Bangka Belitung', 'Bangka Barat'),
      ('Kepulauan Bangka Belitung', 'Belitung Timur'),
      ('Kepulauan Bangka Belitung', 'Kota Pangkal Pinang'),
      ('Kepulauan Riau', 'Bintan'),
      ('Kepulauan Riau', 'Karimun'),
      ('Kepulauan Riau', 'Natuna'),
      ('Kepulauan Riau', 'Lingga'),
      ('Kepulauan Riau', 'Kepulauan Anambas'),
      ('Kepulauan Riau', 'Kota Batam'),
      ('Kepulauan Riau', 'Kota Tanjung Pinang'),
      ('DKI Jakarta', 'Kepulauan Seribu'),
      ('DKI Jakarta', 'Kota Jakarta Pusat'),
      ('DKI Jakarta', 'Kota Jakarta Utara'),
      ('DKI Jakarta', 'Kota Jakarta Barat'),
      ('DKI Jakarta', 'Kota Jakarta Selatan'),
      ('DKI Jakarta', 'Kota Jakarta Timur'),
      ('Jawa Barat', 'Bogor'),
      ('Jawa Barat', 'Sukabumi'),
      ('Jawa Barat', 'Cianjur'),
      ('Jawa Barat', 'Bandung'),
      ('Jawa Barat', 'Garut'),
      ('Jawa Barat', 'Tasikmalaya'),
      ('Jawa Barat', 'Ciamis'),
      ('Jawa Barat', 'Kuningan'),
      ('Jawa Barat', 'Cirebon'),
      ('Jawa Barat', 'Majalengka'),
      ('Jawa Barat', 'Sumedang'),
      ('Jawa Barat', 'Indramayu'),
      ('Jawa Barat', 'Subang'),
      ('Jawa Barat', 'Purwakarta'),
      ('Jawa Barat', 'Karawang'),
      ('Jawa Barat', 'Bekasi'),
      ('Jawa Barat', 'Bandung Barat'),
      ('Jawa Barat', 'Pangandaran'),
      ('Jawa Barat', 'Kota Bogor'),
      ('Jawa Barat', 'Kota Sukabumi'),
      ('Jawa Barat', 'Kota Bandung'),
      ('Jawa Barat', 'Kota Cirebon'),
      ('Jawa Barat', 'Kota Bekasi'),
      ('Jawa Barat', 'Kota Depok'),
      ('Jawa Barat', 'Kota Cimahi'),
      ('Jawa Barat', 'Kota Tasikmalaya'),
      ('Jawa Barat', 'Kota Banjar'),
      ('Jawa Tengah', 'Cilacap'),
      ('Jawa Tengah', 'Banyumas'),
      ('Jawa Tengah', 'Purbalingga'),
      ('Jawa Tengah', 'Banjarnegara'),
      ('Jawa Tengah', 'Kebumen'),
      ('Jawa Tengah', 'Purworejo'),
      ('Jawa Tengah', 'Wonosobo'),
      ('Jawa Tengah', 'Magelang'),
      ('Jawa Tengah', 'Boyolali'),
      ('Jawa Tengah', 'Klaten'),
      ('Jawa Tengah', 'Sukoharjo'),
      ('Jawa Tengah', 'Wonogiri'),
      ('Jawa Tengah', 'Karanganyar'),
      ('Jawa Tengah', 'Sragen'),
      ('Jawa Tengah', 'Grobogan'),
      ('Jawa Tengah', 'Blora'),
      ('Jawa Tengah', 'Rembang'),
      ('Jawa Tengah', 'Pati'),
      ('Jawa Tengah', 'Kudus'),
      ('Jawa Tengah', 'Jepara'),
      ('Jawa Tengah', 'Demak'),
      ('Jawa Tengah', 'Semarang'),
      ('Jawa Tengah', 'Temanggung'),
      ('Jawa Tengah', 'Kendal'),
      ('Jawa Tengah', 'Batang'),
      ('Jawa Tengah', 'Pekalongan'),
      ('Jawa Tengah', 'Pemalang'),
      ('Jawa Tengah', 'Tegal'),
      ('Jawa Tengah', 'Brebes'),
      ('Jawa Tengah', 'Kota Magelang'),
      ('Jawa Tengah', 'Kota Surakarta'),
      ('Jawa Tengah', 'Kota Salatiga'),
      ('Jawa Tengah', 'Kota Semarang'),
      ('Jawa Tengah', 'Kota Pekalongan'),
      ('Jawa Tengah', 'Kota Tegal'),
      ('DI Yogyakarta', 'Kulon Progo'),
      ('DI Yogyakarta', 'Bantul'),
      ('DI Yogyakarta', 'Gunungkidul'),
      ('DI Yogyakarta', 'Sleman'),
      ('DI Yogyakarta', 'Kota Yogyakarta'),
      ('Jawa Timur', 'Pacitan'),
      ('Jawa Timur', 'Ponorogo'),
      ('Jawa Timur', 'Trenggalek'),
      ('Jawa Timur', 'Tulungagung'),
      ('Jawa Timur', 'Blitar'),
      ('Jawa Timur', 'Kediri'),
      ('Jawa Timur', 'Malang'),
      ('Jawa Timur', 'Lumajang'),
      ('Jawa Timur', 'Jember'),
      ('Jawa Timur', 'Banyuwangi'),
      ('Jawa Timur', 'Bondowoso'),
      ('Jawa Timur', 'Situbondo'),
      ('Jawa Timur', 'Probolinggo'),
      ('Jawa Timur', 'Pasuruan'),
      ('Jawa Timur', 'Sidoarjo'),
      ('Jawa Timur', 'Mojokerto'),
      ('Jawa Timur', 'Jombang'),
      ('Jawa Timur', 'Nganjuk'),
      ('Jawa Timur', 'Madiun'),
      ('Jawa Timur', 'Magetan'),
      ('Jawa Timur', 'Ngawi'),
      ('Jawa Timur', 'Bojonegoro'),
      ('Jawa Timur', 'Tuban'),
      ('Jawa Timur', 'Lamongan'),
      ('Jawa Timur', 'Gresik'),
      ('Jawa Timur', 'Bangkalan'),
      ('Jawa Timur', 'Sampang'),
      ('Jawa Timur', 'Pamekasan'),
      ('Jawa Timur', 'Sumenep'),
      ('Jawa Timur', 'Kota Kediri'),
      ('Jawa Timur', 'Kota Blitar'),
      ('Jawa Timur', 'Kota Malang'),
      ('Jawa Timur', 'Kota Probolinggo'),
      ('Jawa Timur', 'Kota Pasuruan'),
      ('Jawa Timur', 'Kota Mojokerto'),
      ('Jawa Timur', 'Kota Madiun'),
      ('Jawa Timur', 'Kota Surabaya'),
      ('Jawa Timur', 'Kota Batu'),
      ('Banten', 'Pandeglang'),
      ('Banten', 'Lebak'),
      ('Banten', 'Tangerang'),
      ('Banten', 'Serang'),
      ('Banten', 'Kota Tangerang'),
      ('Banten', 'Kota Cilegon'),
      ('Banten', 'Kota Serang'),
      ('Banten', 'Kota Tangerang Selatan'),
      ('Bali', 'Jembrana'),
      ('Bali', 'Tabanan'),
      ('Bali', 'Badung'),
      ('Bali', 'Gianyar'),
      ('Bali', 'Klungkung'),
      ('Bali', 'Bangli'),
      ('Bali', 'Karangasem'),
      ('Bali', 'Buleleng'),
      ('Bali', 'Kota Denpasar'),
      ('Nusa Tenggara Barat', 'Lombok Barat'),
      ('Nusa Tenggara Barat', 'Lombok Tengah'),
      ('Nusa Tenggara Barat', 'Lombok Timur'),
      ('Nusa Tenggara Barat', 'Sumbawa'),
      ('Nusa Tenggara Barat', 'Dompu'),
      ('Nusa Tenggara Barat', 'Bima'),
      ('Nusa Tenggara Barat', 'Sumbawa Barat'),
      ('Nusa Tenggara Barat', 'Lombok Utara'),
      ('Nusa Tenggara Barat', 'Kota Mataram'),
      ('Nusa Tenggara Barat', 'Kota Bima'),
      ('Nusa Tenggara Timur', 'Kupang'),
      ('Nusa Tenggara Timur', 'Timor Tengah Selatan'),
      ('Nusa Tenggara Timur', 'Timor Tengah Utara'),
      ('Nusa Tenggara Timur', 'Belu'),
      ('Nusa Tenggara Timur', 'Alor'),
      ('Nusa Tenggara Timur', 'Flores Timur'),
      ('Nusa Tenggara Timur', 'Sikka'),
      ('Nusa Tenggara Timur', 'Ende'),
      ('Nusa Tenggara Timur', 'Ngada'),
      ('Nusa Tenggara Timur', 'Manggarai'),
      ('Nusa Tenggara Timur', 'Sumba Timur'),
      ('Nusa Tenggara Timur', 'Sumba Barat'),
      ('Nusa Tenggara Timur', 'Lembata'),
      ('Nusa Tenggara Timur', 'Rote Ndao'),
      ('Nusa Tenggara Timur', 'Manggarai Barat'),
      ('Nusa Tenggara Timur', 'Nagekeo'),
      ('Nusa Tenggara Timur', 'Sumba Tengah'),
      ('Nusa Tenggara Timur', 'Sumba Barat Daya'),
      ('Nusa Tenggara Timur', 'Manggarai Timur'),
      ('Nusa Tenggara Timur', 'Sabu Raijua'),
      ('Nusa Tenggara Timur', 'Malaka'),
      ('Nusa Tenggara Timur', 'Kota Kupang'),
      ('Kalimantan Barat', 'Sambas'),
      ('Kalimantan Barat', 'Mempawah'),
      ('Kalimantan Barat', 'Sanggau'),
      ('Kalimantan Barat', 'Ketapang'),
      ('Kalimantan Barat', 'Sintang'),
      ('Kalimantan Barat', 'Kapuas Hulu'),
      ('Kalimantan Barat', 'Bengkayang'),
      ('Kalimantan Barat', 'Landak'),
      ('Kalimantan Barat', 'Sekadau'),
      ('Kalimantan Barat', 'Melawi'),
      ('Kalimantan Barat', 'Kayong Utara'),
      ('Kalimantan Barat', 'Kubu Raya'),
      ('Kalimantan Barat', 'Kota Pontianak'),
      ('Kalimantan Barat', 'Kota Singkawang'),
      ('Kalimantan Tengah', 'Kotawaringin Barat'),
      ('Kalimantan Tengah', 'Kotawaringin Timur'),
      ('Kalimantan Tengah', 'Kapuas'),
      ('Kalimantan Tengah', 'Barito Selatan'),
      ('Kalimantan Tengah', 'Barito Utara'),
      ('Kalimantan Tengah', 'Katingan'),
      ('Kalimantan Tengah', 'Seruyan'),
      ('Kalimantan Tengah', 'Sukamara'),
      ('Kalimantan Tengah', 'Lamandau'),
      ('Kalimantan Tengah', 'Gunung Mas'),
      ('Kalimantan Tengah', 'Pulang Pisau'),
      ('Kalimantan Tengah', 'Murung Raya'),
      ('Kalimantan Tengah', 'Barito Timur'),
      ('Kalimantan Tengah', 'Kota Palangkaraya'),
      ('Kalimantan Selatan', 'Tanah Laut'),
      ('Kalimantan Selatan', 'Kotabaru'),
      ('Kalimantan Selatan', 'Banjar'),
      ('Kalimantan Selatan', 'Barito Kuala'),
      ('Kalimantan Selatan', 'Tapin'),
      ('Kalimantan Selatan', 'Hulu Sungai Selatan'),
      ('Kalimantan Selatan', 'Hulu Sungai Tengah'),
      ('Kalimantan Selatan', 'Hulu Sungai Utara'),
      ('Kalimantan Selatan', 'Tabalong'),
      ('Kalimantan Selatan', 'Tanah Bumbu'),
      ('Kalimantan Selatan', 'Balangan'),
      ('Kalimantan Selatan', 'Kota Banjarmasin'),
      ('Kalimantan Selatan', 'Kota Banjarbaru'),
      ('Kalimantan Timur', 'Paser'),
      ('Kalimantan Timur', 'Kutai Kartanegara'),
      ('Kalimantan Timur', 'Berau'),
      ('Kalimantan Timur', 'Kutai Barat'),
      ('Kalimantan Timur', 'Kutai Timur'),
      ('Kalimantan Timur', 'Penajam Paser Utara'),
      ('Kalimantan Timur', 'Mahakam Ulu'),
      ('Kalimantan Timur', 'Kota Balikpapan'),
      ('Kalimantan Timur', 'Kota Samarinda'),
      ('Kalimantan Timur', 'Kota Bontang'),
      ('Kalimantan Utara', 'Bulungan'),
      ('Kalimantan Utara', 'Malinau'),
      ('Kalimantan Utara', 'Nunukan'),
      ('Kalimantan Utara', 'Tana Tidung'),
      ('Kalimantan Utara', 'Kota Tarakan'),
      ('Sulawesi Utara', 'Bolaang Mongondow'),
      ('Sulawesi Utara', 'Minahasa'),
      ('Sulawesi Utara', 'Kepulauan Sangihe'),
      ('Sulawesi Utara', 'Kepulauan Talaud'),
      ('Sulawesi Utara', 'Minahasa Selatan'),
      ('Sulawesi Utara', 'Minahasa Utara'),
      ('Sulawesi Utara', 'Minahasa Tenggara'),
      ('Sulawesi Utara', 'Bolaang Mongondow Utara'),
      ('Sulawesi Utara', 'Kepulauan Siau Tagulandang Biaro (Sitaro)'),
      ('Sulawesi Utara', 'Bolaang Mongondow Timur'),
      ('Sulawesi Utara', 'Bolaang Mongondow Selatan'),
      ('Sulawesi Utara', 'Kota Manado'),
      ('Sulawesi Utara', 'Kota Bitung'),
      ('Sulawesi Utara', 'Kota Tomohon'),
      ('Sulawesi Utara', 'Kota Kotamobagu'),
      ('Sulawesi Tengah', 'Banggai'),
      ('Sulawesi Tengah', 'Poso'),
      ('Sulawesi Tengah', 'Donggala'),
      ('Sulawesi Tengah', 'Toli Toli'),
      ('Sulawesi Tengah', 'Buol'),
      ('Sulawesi Tengah', 'Morowali'),
      ('Sulawesi Tengah', 'Banggai Kepulauan'),
      ('Sulawesi Tengah', 'Parigi Moutong'),
      ('Sulawesi Tengah', 'Tojo Una Una'),
      ('Sulawesi Tengah', 'Sigi'),
      ('Sulawesi Tengah', 'Banggai Laut'),
      ('Sulawesi Tengah', 'Morowali Utara'),
      ('Sulawesi Tengah', 'Kota Palu'),
      ('Sulawesi Selatan', 'Kepulauan Selayar'),
      ('Sulawesi Selatan', 'Bulukumba'),
      ('Sulawesi Selatan', 'Bantaeng'),
      ('Sulawesi Selatan', 'Jeneponto'),
      ('Sulawesi Selatan', 'Takalar'),
      ('Sulawesi Selatan', 'Gowa'),
      ('Sulawesi Selatan', 'Sinjai'),
      ('Sulawesi Selatan', 'Bone'),
      ('Sulawesi Selatan', 'Maros'),
      ('Sulawesi Selatan', 'Pangkajene Kepulauan'),
      ('Sulawesi Selatan', 'Barru'),
      ('Sulawesi Selatan', 'Soppeng'),
      ('Sulawesi Selatan', 'Wajo'),
      ('Sulawesi Selatan', 'Sidenreng Rappang'),
      ('Sulawesi Selatan', 'Pinrang'),
      ('Sulawesi Selatan', 'Enrekang'),
      ('Sulawesi Selatan', 'Luwu'),
      ('Sulawesi Selatan', 'Tana Toraja'),
      ('Sulawesi Selatan', 'Luwu Utara'),
      ('Sulawesi Selatan', 'Luwu Timur'),
      ('Sulawesi Selatan', 'Toraja Utara'),
      ('Sulawesi Selatan', 'Kota Makassar'),
      ('Sulawesi Selatan', 'Kota Pare Pare'),
      ('Sulawesi Selatan', 'Kota Palopo'),
      ('Sulawesi Tenggara', 'Kolaka'),
      ('Sulawesi Tenggara', 'Konawe'),
      ('Sulawesi Tenggara', 'Muna'),
      ('Sulawesi Tenggara', 'Buton'),
      ('Sulawesi Tenggara', 'Konawe Selatan'),
      ('Sulawesi Tenggara', 'Bombana'),
      ('Sulawesi Tenggara', 'Wakatobi'),
      ('Sulawesi Tenggara', 'Kolaka Utara'),
      ('Sulawesi Tenggara', 'Konawe Utara'),
      ('Sulawesi Tenggara', 'Buton Utara'),
      ('Sulawesi Tenggara', 'Kolaka Timur'),
      ('Sulawesi Tenggara', 'Konawe Kepulauan'),
      ('Sulawesi Tenggara', 'Muna Barat'),
      ('Sulawesi Tenggara', 'Buton Tengah'),
      ('Sulawesi Tenggara', 'Buton Selatan'),
      ('Sulawesi Tenggara', 'Kota Kendari'),
      ('Sulawesi Tenggara', 'Kota Bau Bau'),
      ('Gorontalo', 'Gorontalo'),
      ('Gorontalo', 'Boalemo'),
      ('Gorontalo', 'Bone Bolango'),
      ('Gorontalo', 'Pahuwato'),
      ('Gorontalo', 'Gorontalo Utara'),
      ('Gorontalo', 'Kota Gorontalo'),
      ('Sulawesi Barat', 'Pasangkayu (Mamuju Utara)'),
      ('Sulawesi Barat', 'Mamuju'),
      ('Sulawesi Barat', 'Mamasa'),
      ('Sulawesi Barat', 'Polewali Mandar'),
      ('Sulawesi Barat', 'Majene'),
      ('Sulawesi Barat', 'Mamuju Tengah'),
      ('Maluku', 'Maluku Tengah'),
      ('Maluku', 'Maluku Tenggara'),
      ('Maluku', 'Kepulauan Tanimbar (Maluku Tenggara Barat)'),
      ('Maluku', 'Buru'),
      ('Maluku', 'Seram Bagian Timur'),
      ('Maluku', 'Seram Bagian Barat'),
      ('Maluku', 'Kepulauan Aru'),
      ('Maluku', 'Maluku Barat Daya'),
      ('Maluku', 'Buru Selatan'),
      ('Maluku', 'Kota Ambon'),
      ('Maluku', 'Kota Tual'),
      ('Maluku Utara', 'Halmahera Barat'),
      ('Maluku Utara', 'Halmahera Tengah'),
      ('Maluku Utara', 'Halmahera Utara'),
      ('Maluku Utara', 'Halmahera Selatan'),
      ('Maluku Utara', 'Kepulauan Sula'),
      ('Maluku Utara', 'Halmahera Timur'),
      ('Maluku Utara', 'Pulau Morotai'),
      ('Maluku Utara', 'Pulau Taliabu'),
      ('Maluku Utara', 'Kota Ternate'),
      ('Maluku Utara', 'Kota Tidore Kepulauan'),
      ('Papua', 'Jayapura'),
      ('Papua', 'Kepulauan Yapen'),
      ('Papua', 'Biak Numfor'),
      ('Papua', 'Sarmi'),
      ('Papua', 'Keerom'),
      ('Papua', 'Waropen'),
      ('Papua', 'Supiori'),
      ('Papua', 'Mamberamo Raya'),
      ('Papua', 'Kota Jayapura'),
      ('Papua Barat', 'Manokwari'),
      ('Papua Barat', 'Fak Fak'),
      ('Papua Barat', 'Teluk Bintuni'),
      ('Papua Barat', 'Teluk Wondama'),
      ('Papua Barat', 'Kaimana'),
      ('Papua Barat', 'Manokwari Selatan'),
      ('Papua Barat', 'Pegunungan Arfak'),
      ('Papua Selatan', 'Merauke'),
      ('Papua Selatan', 'Boven Digoel'),
      ('Papua Selatan', 'Mappi'),
      ('Papua Selatan', 'Asmat'),
      ('Papua Tengah', 'Nabire'),
      ('Papua Tengah', 'Puncak Jaya'),
      ('Papua Tengah', 'Paniai'),
      ('Papua Tengah', 'Mimika'),
      ('Papua Tengah', 'Puncak'),
      ('Papua Tengah', 'Dogiyai'),
      ('Papua Tengah', 'Intan Jaya'),
      ('Papua Tengah', 'Deiyai'),
      ('Papua Pegunungan', 'Jayawijaya'),
      ('Papua Pegunungan', 'Pegunungan Bintang'),
      ('Papua Pegunungan', 'Yahukimo'),
      ('Papua Pegunungan', 'Tolikara'),
      ('Papua Pegunungan', 'Mamberamo Tengah'),
      ('Papua Pegunungan', 'Yalimo'),
      ('Papua Pegunungan', 'Lanny Jaya'),
      ('Papua Pegunungan', 'Nduga'),
      ('Papua Barat Daya', 'Sorong'),
      ('Papua Barat Daya', 'Sorong Selatan'),
      ('Papua Barat Daya', 'Raja Ampat'),
      ('Papua Barat Daya', 'Tambrauw'),
      ('Papua Barat Daya', 'Maybrat'),
      ('Papua Barat Daya', 'Kota Sorong')
    ) AS v(province_name, city_name)
    JOIN geo_states gs ON gs.country_code = 'ID' AND gs.name = v.province_name
    ON CONFLICT (state_id, name) DO NOTHING;
  END IF;
END $$;
